/**
 * The two halves must name the same person the same way.
 *
 * The bug this covers was visible on one screen: the dashboard resolved ids from
 * `pipeline/data/user_names.json` while the bot rendered them raw, so a work item
 * read as a name on the web page and as `U07T3KYHYQK` in Slack — and inside one
 * Slack card, the timeline (resolved by the pipeline before it left) sat above an
 * evidence line that still showed the id.
 *
 * The pseudonym expectations below are not invented here. They were generated by
 * the Python side:
 *
 *     python3 -c "import sys; sys.path.insert(0,'.'); \
 *       from tam.ingest.users import pseudonym; print(pseudonym('U0DEMOUSER1'))"
 *
 * so a drift in either implementation — a reordered pool, a different hash, a
 * changed surname table — fails here rather than on a screenshot where nobody can
 * tell which of the two is wrong.
 */
import { test, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import {
  describeNames, displayName, isSlackId, mentionOf, namesInText, nameMode, pseudonym, resetNames,
} from '../src/names.js';
import { people } from '../src/blocks/common.js';

let dir: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'meowtam-names-'));
  delete process.env.TAM_NAMES;
  process.env.TAM_NAMES_PATH = join(dir, 'user_names.json');
  resetNames();
});

afterEach(() => {
  delete process.env.TAM_NAMES;
  delete process.env.TAM_NAMES_PATH;
  resetNames();
});

/** Generated by tam.ingest.users.pseudonym — see the header. */
const FROM_PYTHON: Array<[string, string]> = [
  ['U0DEMOUSER1', 'เก่ง ธ.'],
  ['U0EXAMPLE12', 'แก้ม ม.'],
  ['W012345678', 'โดม ส.'],
  ['USLACKBOT', 'ภูมิ ณ.'],
  ['B01ABCDEF', 'บอทแจ้งเตือน'],
];

test('pseudonyms match the Python implementation byte for byte', () => {
  for (const [id, expected] of FROM_PYTHON) {
    assert.equal(pseudonym(id), expected, `pseudonym(${id})`);
  }
});

test('a bot id gets a bot label, so an integration never reads as a colleague', () => {
  assert.equal(pseudonym('B0B2RD5D1NF').startsWith('บอท') || pseudonym('B0B2RD5D1NF') === 'ผู้ช่วย AI', true);
  assert.equal(pseudonym('B01ABCDEF').includes('.'), false, 'bots get no surname initial');
});

test('id shape: the same values the Python side accepts', () => {
  assert.equal(isSlackId('U07T3KYHYQK'), true);
  assert.equal(isSlackId('W012345678'), true);
  assert.equal(isSlackId('B0B2RD5D1NF'), true);
  // Too short to be a real id — the sample corpus uses these, and they must pass
  // through as text rather than being resolved to somebody.
  assert.equal(isSlackId('U01FE'), false);
  assert.equal(isSlackId('Alice'), false);
  assert.equal(isSlackId('U0demouser1'), false, 'lowercase is not an id');
});

test('non-ids pass through untouched in every mode', () => {
  for (const mode of ['slack', 'pseudonym', 'id']) {
    process.env.TAM_NAMES = mode;
    resetNames();
    assert.equal(displayName('Alice'), 'Alice');
    assert.equal(displayName('U01FE'), 'U01FE');
    assert.equal(displayName(''), '');
    assert.equal(displayName(undefined), '');
  }
});

test('slack mode reads the shared cache the pipeline writes', () => {
  writeFileSync(process.env.TAM_NAMES_PATH as string, JSON.stringify({ U07T3KYHYQK: 'แนน สมชาย' }), 'utf8');
  process.env.TAM_NAMES = 'slack';
  resetNames();
  assert.equal(displayName('U07T3KYHYQK'), 'แนน สมชาย');
  // An id the fetch never saw still has to render as something readable, and that
  // something is its pseudonym. `--check` is what lists these.
  assert.equal(displayName('U0DEMOUSER1'), 'เก่ง ธ.');
});

test('id mode keeps the raw key, for debugging a join', () => {
  process.env.TAM_NAMES = 'id';
  resetNames();
  assert.equal(displayName('U0DEMOUSER1'), 'U0DEMOUSER1');
});

test('a name cache written while the bot is running is picked up', () => {
  const path = process.env.TAM_NAMES_PATH as string;
  writeFileSync(path, JSON.stringify({ U0DEMOUSER1: 'ชื่อแรก' }), 'utf8');
  process.env.TAM_NAMES = 'slack';
  resetNames();
  assert.equal(displayName('U0DEMOUSER1'), 'ชื่อแรก');
  writeFileSync(path, JSON.stringify({ U0DEMOUSER1: 'ชื่อที่แก้แล้ว' }), 'utf8');
  resetNames(); // what `/meowtam reload` does
  assert.equal(displayName('U0DEMOUSER1'), 'ชื่อที่แก้แล้ว');
});

test('mentions inside a message body are resolved, bare ids in quoted text are not', () => {
  process.env.TAM_NAMES = 'pseudonym';
  resetNames();
  assert.equal(namesInText('@U0DEMOUSER1 ช่วยดีพลอยให้ด้วย'), '@เก่ง ธ. ช่วยดีพลอยให้ด้วย');
  assert.equal(namesInText('log says user=U0DEMOUSER1 failed'), 'log says user=U0DEMOUSER1 failed');
});

test('pseudonym mode never posts a real Slack mention', () => {
  process.env.TAM_NAMES = 'pseudonym';
  resetNames();
  // `<@U0…>` would make Slack render the real display name client-side, putting a
  // real name into the very screenshot this mode exists to keep clean.
  assert.equal(mentionOf('U0DEMOUSER1'), 'เก่ง ธ.');
  process.env.TAM_NAMES = 'slack';
  resetNames();
  assert.equal(mentionOf('U0DEMOUSER1'), '<@U0DEMOUSER1>');
});

test('participants render as people, and only stay code chips in id mode', () => {
  process.env.TAM_NAMES = 'pseudonym';
  resetNames();
  assert.equal(people(['U0DEMOUSER1', 'Alice']), 'เก่ง ธ., Alice');
  assert.equal(people(['U0DEMOUSER1']).includes('`'), false);
  process.env.TAM_NAMES = 'id';
  resetNames();
  assert.equal(people(['U0DEMOUSER1']), '`U0DEMOUSER1`');
});

test('mode defaults on the cache, never to raw ids', () => {
  resetNames();
  assert.equal(nameMode(), 'pseudonym', 'no cache → pseudonyms, not keys');
  writeFileSync(process.env.TAM_NAMES_PATH as string, JSON.stringify({ U0DEMOUSER1: 'แนน' }), 'utf8');
  resetNames();
  assert.equal(nameMode(), 'slack');
  assert.match(describeNames(), /ชื่อจริง 1 คน/);
});

test('a typo in TAM_NAMES fails loudly instead of falling back to real names', () => {
  process.env.TAM_NAMES = 'pseudonyms'; // plural — the plausible typo
  resetNames();
  assert.throws(() => nameMode(), /TAM_NAMES=pseudonyms/);
});

test('a corrupt cache degrades to pseudonyms instead of taking the bot down', () => {
  writeFileSync(process.env.TAM_NAMES_PATH as string, '{ this is not json', 'utf8');
  process.env.TAM_NAMES = 'slack';
  resetNames();
  assert.equal(displayName('U0DEMOUSER1'), 'เก่ง ธ.');
});
