/**
 * Slack user ids → something a person can read, on the bot side.
 *
 * This is the TypeScript half of `pipeline/tam/ingest/users.py`, and it exists
 * because the two halves were disagreeing on screen. The dashboard resolved ids
 * at render time from a local cache; the bot did not resolve them at all, so the
 * same work item read as "แนน ก." on the web page and as `U07T3KYHYQK` in Slack —
 * and inside a single Slack card the timeline rendered names (the pipeline had
 * already resolved those) while the evidence line above it rendered ids. That mix
 * is worse than either extreme: a reader cannot tell whether two rows are the
 * same person.
 *
 * Same rules as the Python module, deliberately:
 *
 *   - Resolution happens at DISPLAY time. Stored records keep the id, because the
 *     id is what joins a message to its thread and a human correction to the
 *     thing it corrects.
 *   - Real names live in ONE local file, `pipeline/data/user_names.json`, written
 *     by `python3 -m tam.ingest.users --fetch` and gitignored. Both halves read
 *     it, so both halves say the same name.
 *   - `TAM_NAMES=pseudonym` renders stable invented names instead. The pools and
 *     the sha1 derivation below are byte-for-byte the Python ones, so the same id
 *     gets the same pseudonym in Slack and on the dashboard. `tests/names.test.ts`
 *     pins that with values generated by the Python side.
 */

import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

/** The pipeline's cache, shared on purpose. One file that says who is who. */
export function namesPath(): string {
  const configured = (process.env.TAM_NAMES_PATH ?? '').trim();
  return configured ? resolve(configured) : resolve(here, '../../pipeline/data/user_names.json');
}

// Kept in sync with tam/ingest/users.py. Order matters: the pseudonym is an index
// into these, so reordering a pool renames people.
const PSEUDONYMS = [
  'ก้อง', 'แนน', 'ต้น', 'ฟ้า', 'บอส', 'มิ้น', 'เอิร์ธ', 'ปอ', 'หนึ่ง', 'จูน',
  'โดม', 'แพร', 'กัน', 'อิ๋ว', 'ภูมิ', 'ตาล', 'เจ', 'นิว', 'หมิว', 'ป่าน',
  'อาร์ม', 'เบล', 'ดิว', 'พลอย', 'เก่ง', 'ญาญ่า', 'ท็อป', 'ขวัญ', 'วิน', 'แก้ม',
] as const;
const BOT_PSEUDONYMS = ['บอทแจ้งเตือน', 'บอทดีพลอย', 'บอทรายงาน', 'ผู้ช่วย AI'] as const;
const SURNAME_INITIALS = [
  'ก', 'จ', 'ช', 'ณ', 'ด', 'ต', 'ท', 'ธ', 'น', 'บ',
  'ป', 'พ', 'ภ', 'ม', 'ย', 'ร', 'ล', 'ว', 'ส', 'อ',
] as const;

/** `@U0123…` as the pipeline leaves it inside a message body. */
const MENTION = /@([UWB][A-Z0-9]{7,})\b/g;

export type NameMode = 'slack' | 'pseudonym' | 'id';

/**
 * True for something shaped like a Slack user or bot id, not a name.
 *
 * A corpus is a mix: meeting transcripts carry speaker names already, and
 * `scripts/build-ledger.ts` writes display names into the ledger. Only the ids
 * need resolving, and everything else has to pass through untouched.
 */
export function isSlackId(value: string): boolean {
  if (value.length < 8 || !'UWB'.includes(value[0] as string)) return false;
  const rest = value.slice(1).replace(/_/g, '');
  return rest.length > 0 && /^[0-9A-Z]+$/.test(rest);
}

function cacheExists(): boolean {
  try {
    return statSync(namesPath()).isFile();
  } catch {
    return false;
  }
}

let modeCache: NameMode | null = null;

/**
 * Configured mode, defaulting on whether the real-name cache exists.
 *
 * Never defaults to `id`: the id was the complaint. An unset `TAM_NAMES` with no
 * cache means pseudonyms, which are readable and identify nobody.
 */
export function nameMode(): NameMode {
  if (modeCache) return modeCache;
  const configured = (process.env.TAM_NAMES ?? '').trim().toLowerCase();
  if (configured === 'slack' || configured === 'pseudonym' || configured === 'id') {
    modeCache = configured;
  } else if (configured) {
    // Boot-time failure, like the Python SystemExit. A typo that silently fell
    // back to real names is a privacy bug, not a formatting one.
    throw new Error(`TAM_NAMES=${configured} ไม่ใช่ slack, pseudonym หรือ id`);
  } else {
    modeCache = cacheExists() ? 'slack' : 'pseudonym';
  }
  return modeCache;
}

let cached: { mtimeMs: number; path: string; names: Record<string, string> } | null = null;
let checkedAt = 0;

/**
 * The id → name cache, re-read when the file changes.
 *
 * The bot is long-running: someone fetches names *while* it is up and expects the
 * next `/meowtam` to show them, without a restart. The stat is throttled to once
 * a second so rendering a digest of two hundred rows does not stat two hundred
 * times.
 */
export function knownNames(): Record<string, string> {
  if (nameMode() !== 'slack') return {};
  const path = namesPath();
  const now = Date.now();
  if (cached && cached.path === path && now - checkedAt < 1000) return cached.names;
  checkedAt = now;
  let mtimeMs: number;
  try {
    mtimeMs = statSync(path).mtimeMs;
  } catch {
    cached = { mtimeMs: 0, path, names: {} };
    return cached.names;
  }
  if (cached && cached.path === path && cached.mtimeMs === mtimeMs) return cached.names;
  try {
    const parsed = JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
    const names: Record<string, string> = {};
    for (const [id, name] of Object.entries(parsed ?? {})) {
      const text = String(name ?? '').trim();
      if (text) names[id] = text;
    }
    cached = { mtimeMs, path, names };
  } catch (err) {
    // A corrupt cache must not take the bot down mid-standup: ids still render,
    // and the log says which file to re-fetch.
    console.error(`อ่าน ${path} ไม่ได้ (${(err as Error).message}) — re-fetch: python3 -m tam.ingest.users --fetch`);
    cached = { mtimeMs, path, names: {} };
  }
  return cached.names;
}

/** Drop the cached mode and names. Called by `/meowtam reload` and by tests. */
export function resetNames(): void {
  modeCache = null;
  cached = null;
  checkedAt = 0;
}

/**
 * A stable invented name for one id — first name plus a surname initial, the way
 * a Thai team roster is written. sha1, not a per-process hash, so the same person
 * reads as the same name after a restart and across the two languages.
 */
export function pseudonym(userId: string): string {
  const pool = userId.startsWith('B') ? BOT_PSEUDONYMS : PSEUDONYMS;
  const digest = createHash('sha1').update(userId, 'utf8').digest();
  const name = pool[(digest[0] as number) % pool.length] as string;
  if (pool === BOT_PSEUDONYMS) return name; // already descriptive; bots get no surname
  return `${name} ${SURNAME_INITIALS[(digest[1] as number) % SURNAME_INITIALS.length]}.`;
}

/**
 * One user field, rendered. Non-ids pass through unchanged.
 *
 * In `slack` mode an id that is missing from the cache falls through to its
 * pseudonym rather than showing the raw key — usually somebody who joined after
 * the last fetch, and the reader is no better served by `U07…` than by a label.
 * `python3 -m tam.ingest.users --check` lists exactly those ids.
 */
export function displayName(value: unknown): string {
  const text = String(value ?? '').trim();
  if (!text || !isSlackId(text)) return text;
  const mode = nameMode();
  if (mode === 'id') return text;
  if (mode === 'slack') return knownNames()[text] || pseudonym(text);
  return pseudonym(text);
}

export function displayAll(values: Iterable<unknown>): string[] {
  return [...values].map((v) => displayName(v));
}

/**
 * Rewrite `@U0123…` mentions inside a message body.
 *
 * Only the mention form is touched. A bare id in prose is usually somebody
 * quoting a log line, and rewriting that would change a quoted fact.
 */
export function namesInText(text: unknown): string {
  return String(text ?? '').replace(MENTION, (_m, id: string) => '@' + displayName(id));
}

/**
 * How to address a person in text the bot posts to Slack.
 *
 * `<@U07…>` is the right thing in `slack` mode: Slack renders the real display
 * name client-side and the mention notifies them. In the other two modes it is
 * exactly the wrong thing — the point of `TAM_NAMES=pseudonym` is a screenshot
 * with no real names in it, and Slack would put one back. So those modes get
 * plain resolved text and no ping.
 */
export function mentionOf(userId: string): string {
  const id = String(userId ?? '').trim();
  if (!id) return '';
  if (nameMode() === 'slack' && isSlackId(id)) return `<@${id}>`;
  return displayName(id) || id;
}

/** One line for the boot banner, so the mode is never a surprise. */
export function describeNames(): string {
  const mode = nameMode();
  if (mode === 'id') return 'ชื่อผู้ใช้: id ดิบ (TAM_NAMES=id)';
  if (mode === 'pseudonym') return 'ชื่อผู้ใช้: ชื่อสมมุติ (TAM_NAMES=pseudonym) — ไม่ระบุตัวบุคคล';
  const count = Object.keys(knownNames()).length;
  return count
    ? `ชื่อผู้ใช้: ชื่อจริง ${count} คน จาก ${namesPath()}`
    : `ชื่อผู้ใช้: ยังไม่มี cache (${namesPath()}) — ใช้ชื่อสมมุติ · ดึงด้วย python3 -m tam.ingest.users --fetch`;
}
